# Generated by Django 4.2.14 on 2024-08-07 08:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agentDatabase',
            fields=[
                ('id', models.IntegerField(default=api.models.auto_increment, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('realName', models.CharField(default='', max_length=50)),
                ('rank', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B')], default='S', max_length=1)),
                ('fightingStyle', models.CharField(choices=[('Attack', 'Attack'), ('Stun', 'Stun'), ('Anomaly', 'Anomaly'), ('Support', 'Support'), ('Defense', 'Defense')], default='', max_length=50)),
                ('faction', models.CharField(choices=[('Victoria Housekeeping', 'Victoria Housekeeping'), ('Belobog Heavy Industries', 'Belobog Heavy Industries'), ('Criminal Investigation Special Response Team', 'Criminal Investigation Special Response Team'), ('Cunning Hares', 'Cunning Hares'), ('Obol Squad', 'Obol Squad'), ('Section 6', 'Section 6'), ('Sons of Calydon', 'Sons of Calydon')], default='', max_length=50)),
                ('moduleType', models.CharField(choices=[('Slash', 'Slash'), ('Pierce', 'Pierce'), ('Strike', 'Strike')], default='', max_length=20)),
                ('icon', models.ImageField(default='', upload_to='uploads/agents/')),
            ],
        ),
    ]
