# Generated by Django 5.1 on 2024-08-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_agentdatabase_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdatabase',
            name='attribute',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Electric', 'Electric'), ('Fire', 'Fire'), ('Ice', 'Ice'), ('Ether', 'Ether')], default='', max_length=20),
        ),
    ]
