# Generated by Django 5.1 on 2024-08-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agentdatabase_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentdatabase',
            old_name='icon',
            new_name='nameIcon',
        ),
        migrations.AddField(
            model_name='agentdatabase',
            name='attributeIcon',
            field=models.ImageField(default='', editable=False, upload_to=''),
        ),
    ]
