# Generated by Django 5.1 on 2024-08-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_icon_agentdatabase_nameicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdatabase',
            name='factionIcon',
            field=models.ImageField(default='', editable=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='agentdatabase',
            name='fightingStyleIcon',
            field=models.ImageField(default='', editable=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='agentdatabase',
            name='moduleTypeIcon',
            field=models.ImageField(default='', editable=False, upload_to=''),
        ),
    ]
