# Generated by Django 4.2.14 on 2024-08-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_agentdatabase_factionicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdatabase',
            name='rankIcon',
            field=models.ImageField(default='', editable=False, upload_to=''),
        ),
    ]
