# Generated by Django 4.2.14 on 2024-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_agentdatabase_stat_alter_agentdatabase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdatabase',
            name='stat',
            field=models.JSONField(default=dict),
        ),
    ]
