# Generated by Django 4.2.14 on 2024-08-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_agentdatabase_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentdatabase',
            old_name='stat',
            new_name='baseStat',
        ),
        migrations.AlterField(
            model_name='agentdatabase',
            name='nameIcon',
            field=models.ImageField(default='', upload_to='agents/'),
        ),
    ]
