# Generated by Django 4.2.14 on 2024-08-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_stat_agentdatabase_basestat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='agentDatabase',
            new_name='agentModel',
        ),
    ]
